baseurl: '/teatro_lirico'
permalink: pretty
title: 'Teatro Lirico'

google_analytics_id: ""

homepage:
  show_call_box: true

logo:
  mobile: "images/logo/logo.jpg"
  desktop: "images/logo/logo.jpg"
  desktop_height: "36px"

footer:
  copyright_text: 'Site by Two Beautiful Geeks '

seo:
  meta_og_title: "Teatro Lirico"
  meta_og_type: "website"
  meta_og_url: "https://twobeautifulgeeks.github.io/"
  meta_og_image: 
  meta_og_description: "Teatro Lirico"
  meta_twitter_card: "summary"
  meta_twitter_site: 
  meta_twitter_creator: 

collections:
  services:
    output: true
  team:
    output: true

sass:
  indentWidth: 4
  style: compact # possible values: nested expanded compact compressed
  precision: 10

plugins:
  - jekyll-environment-variables

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md